workflows:
  clima-workflow:
    name: Clima Pipeline
    scripts:
      - name: CICD Started
        script: echo "Starting Clima Pipeline"
    publishing:
      email:
        recipients:
        - wdarchenemy@gmail.com
